### ISSUE TITLE
Packer plugin not working well with VMware Fusion Pro 13.0 on M1-based chipset.

### ISSUE THREAD

**Issue by yhuang** [hashicorp/packer-plugin-vmware#108]
#### Overview of the Issue

`packer build <template>` command dies immediately upon launch with the following error message:

```
2022/12/26 19:56:46 packer-builder-vmware-iso plugin: Executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -T fusion start builds/rocky9-base/rocky9-base.vmx nogui
2022/12/26 19:56:46 packer-builder-vmware-iso plugin: stdout: 2022-12-26T19:56:46.812| ServiceImpl_Opener: PID 10561
2022/12/26 19:56:46 packer-builder-vmware-iso plugin: Error: The operation was canceled
2022/12/26 19:56:46 packer-builder-vmware-iso plugin: stderr:
==> vmware-iso: Error: The operation was canceled
==> vmware-iso: Error starting VM: VMware error: 2022-12-26T19:56:46.812| ServiceImpl_Opener: PID 10561
==> vmware-iso: Error: The operation was canceled
```

Upon closer examination of the available vmware.log, I found more clarifying details about the specific error condition:

```
2022-12-26T08:22:01.269Z In(05) vmx Command line: "/Applications/VMware Fusion.app/Contents/Library/vmware-vmx" "-s" "vmx.noUIBuildNumberCheck=TRUE" "-#" "product=1;name=vmrun;version=1.17.0;buildnumber=20802013;licensename=VMware Fusion for Mac OS;licenseversion=13.0;" "-@" "duplex=3;msgs=ui" "/Users/<<user>/workspace/sandboxes/builds/rocky9-base/rocky9-base.vmx"
2022-12-26T08:22:01.269Z In(05) vmx Msg_SetLocaleEx: HostLocale=UTF-8 UserLocale=en
.
.
.
2022-12-26T08:22:01.361Z In(05) vmx Msg_Post: Error
2022-12-26T08:22:01.361Z In(05) vmx [msg.guestos.badArch] This virtual machine cannot be powered on because it requires the X86 machine architecture, which is incompatible with this Arm machine architecture host. See KB-84273.
2022-12-26T08:22:01.361Z In(05) vmx ----------------------------------------
2022-12-26T08:22:01.361Z In(05) vmx MsgIsAnswered: Using builtin default 'OK' as the answer for 'msg.guestos.badArch'
2022-12-26T08:22:01.361Z In(05) vmx Module 'GuestOS' power on failed.

```

I was able to build a guest VM manually using VMware Fusion Pro 13.0 on my MacBook Air with M1 without issue.  When reviewing the vmware.log from that successful run, I noticed the generated command-line for the `vmware-vmx` invocation was different.  The options after the Product-specific settings (after the `-#` flag) had `product=64`, instead of `product=1` as seen from the `packer`-generated command-line.

```
2022-12-27T03:15:27.776Z In(05) vmx Command line: "/Applications/VMware Fusion.app/Contents/Library/vmware-vmx" "-E" "en" "-s" "vmx.stdio.keep=TRUE" "-#" "product=64;name=VMware Fusion;version=13.0.0;buildnumber=20802013;licensename=VMware Fusion for Mac OS;licenseversion=13.0;" "-@" "duplex=3;msgs=ui" "-D" "4" "/Users/<user>/Virtual Machines.localized/rocky-minimal-base.vmwarevm/rocky-minimal-base.vmx"
```

#### System Setup

System:  MacBook Air, M1 2020
OS:  macOS Ventura 13.1
Hypervisor Software: VMware Fusion Pro 13.0
Packer Version: 1.8.5
Packer Plugin:  packer-plugin-vmware_v1.0.7_x5.0_darwin_arm64

#### Full VMware Log
https://gist.github.com/yhuang/2d872ae318e3d293d38aa9bc312389b1

#### Packer Log
https://gist.github.com/yhuang/b6ba61121a19f8317993fca0c096a5aa

**Comment by lbajolet-hashicorp** [comment]
Hi @yhuang,

That one may be tricky, I don't see us setting the `product=1` manually, so I suspect this may be linked to the `vmx` file we generate when creating the VM.

Out of curiosity, would you mind sharing the vmx file you have for the VM you built manually? Maybe we can play spot the difference and see what we can include here?

Also for helping understand the context, would you be able to share the Packer template (maybe a shortened version if it's too large) so we can take a look at what your configuration looks like?

@tenthirtyam, what do you think about this? Apologies in advance if my guess is wrong, I'm not an expert when it comes to VMWare products, so I'll probably need your help fixing this one.

**Comment by yhuang** [comment]
@lbajolet-hashicorp : Thank you for taking a closer look at this issue.  I have included the vmx file from the manually built VM here:

https://gist.github.com/yhuang/8a1b02078eda0218a79a76c7de89ee2d

I have also shared my packer template here:

https://gist.github.com/yhuang/84e63b63f3df60fc79ca234eb409f571

Thank You.

**Comment by lbajolet-hashicorp** [comment]
OK there are a number of things that pop to me, bear in mind this may not be one of those, but we can see:

* `virtualHW.version`: we set it to 8 in the `vmx` that we generate, this might be a limitation of the version we're picking here. I would suggest first to change this to `20`. I think you may be able to set it through the `vmx_data` option for the builder.
* `firmware = "efi"`: this is something we don't manually set, and in this case might be defaulting to `bios`? If the previous change does not fix the issue, we can consider trying this.

If you have time, would you mind testing those?

For reference, here's what the section may look like in your template:

```hcl
build "vmware-iso" "test" {
    [...]
    vmx_data = {
        "virtualHW.version" = "20"
    }
}
```

**Comment by yhuang** [comment]
Hi @lbajolet-hashicorp : The errors seem slightly different, but the end result remains the same:

vmware.log: https://gist.github.com/yhuang/e2e3ddedd9f6d19f9fb7b412689f6d60
vmx: https://gist.github.com/yhuang/5836f7f25c61f7f75f881d47ca54f599

```
      "vmx_data": {
        "firmware": "efi",
        "virtualHW.version": "20"
      },

...

Warning: Warning when preparing build: "vmware-iso"

Your vmx data contains the following variable(s), which Packer normally sets
when it generates its own default vmx template. This may cause your build to
fail or behave unpredictably: virtualHW.version


vmware-iso: output will be in this color.

==> vmware-iso: Retrieving ISO
==> vmware-iso: Trying iso/Rocky-9.1-aarch64-minimal.iso
==> vmware-iso: Trying iso/Rocky-9.1-aarch64-minimal.iso?checksum=sha256%3A16edc2842bc31f845cb665ee8333ec05032418d5c010489040031f62f14bacf5
==> vmware-iso: iso/Rocky-9.1-aarch64-minimal.iso?checksum=sha256%3A16edc2842bc31f845cb665ee8333ec05032418d5c010489040031f62f14bacf5 => /Users/yhuang/workspace/sandboxes/iso/Rocky-9.1-aarch64-minimal.iso
==> vmware-iso: Configuring output and export directories...
==> vmware-iso: Creating required virtual machine disks
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8094
==> vmware-iso: Starting virtual machine...
    vmware-iso: The VM will be run headless, without a GUI. If you want to
    vmware-iso: view the screen of the VM, connect via VNC with the password "K5wQtyTr" to
    vmware-iso: vnc://127.0.0.1:5974
==> vmware-iso: Error starting VM: VMware error: 2023-01-05T16:57:34.573| ServiceImpl_Opener: PID 60159
==> vmware-iso: Error: The operation was canceled
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored after 6 seconds 394 milliseconds: Error starting VM: VMware error: 2023-01-05T16:57:34.573| ServiceImpl_Opener: PID 60159
Error: The operation was canceled

==> Wait completed after 6 seconds 394 milliseconds

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Error starting VM: VMware error: 2023-01-05T16:57:34.573| ServiceImpl_Opener: PID 60159
Error: The operation was canceled

==> Builds finished but no artifacts were created.
```

**Comment by tenthirtyam** [comment]
Apologies, but I don’t have a Mac with Apple Silicone to test this; however, curious if setting `architecture = "arm64"` in the vmx_data parameters may assist.

**Comment by yhuang** [comment]
vmware.log with architecture = arm64: https://gist.github.com/yhuang/7013d99237db1d247abada474f988c9a
vmx log with architecture = arm64: https://gist.github.com/yhuang/943ab922b6c96691ceee270e7dbc5dd6

I still think the issue is with packer/vmware plugin's inability to produce the appropriate `vmrun` command:

```
"/Applications/VMware Fusion.app/Contents/Library/vmware-vmx" "-s" "vmx.noUIBuildNumberCheck=TRUE" "-#" "product=1;name=vmrun;version=1.17.0;buildnumber=20802013;licensename=VMware Fusion for Mac OS;licenseversion=13.0;" "-@" "duplex=3;msgs=ui" "/Users/<user>/workspace/sandboxes/builds/rocky9-base/rocky9-base.vmx"
```

https://gist.github.com/yhuang/7013d99237db1d247abada474f988c9a#file-vmware-log-arm64-L68

There should be a way for users to specify `product=64` if one does not exist already.

**Comment by lbajolet-hashicorp** [comment]
@yhuang, with the change @tenthirtyam proposed, does it work as expected?

Regarding the `product=64`, I'm not sure this is something we have agency on, since we don't call `vmware-vmx` directly, so the rest of the command-line is, I assume, produced by `vmrun -T fusion start`.
Again pardon my ignorance, I'm not well-versed in VMWare and its commands.

From the looks of it though, if the architecture setting does fix the problem, I would think we can add an option to set that in the configuration for the template, this way you can specify whether you want x86-64/arm/other more easily than through the `vmx_data` map.

Would that work for you?
@tenthirtyam, what do you think? Is it an acceptable solution in your book?

If we go that route, we will probably want to check that the values are accepted before amending the generated vmx, is there a documentation on what this argument accepts in a vmx file?

**Comment by yhuang** [comment]
@lbajolet-hashicorp : The outcome from the changes @tenthirtyam proposed was posted in my last comment.

vmware.log with architecture = arm64: https://gist.github.com/yhuang/7013d99237db1d247abada474f988c9a
vmx log with architecture = arm64: https://gist.github.com/yhuang/943ab922b6c96691ceee270e7dbc5dd6

 The build still fails.  I understand `packer-plugin-vmware` plugin is not calling `vmware-vmx` directly today, but perhaps the interactions between the plugin and `vmware-vmx` need to evolve in order to support `packer` users with M1 laptops.  Would that conversation need to involve VMware?  Would HashiCorp need a current customer to advocate for that three-party discussion?  Thank you.

**Comment by tenthirtyam** [comment]
I'm at VMware and an external project collaborator in my spare time. 😉 

Already notified the Fusion PM for this one and another open F13 issue. 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by yhuang** [comment]
Thank you for representing VMware, @tenthirtyam.  I have been using Fusion since version 7 on all my Mac laptops.  Since getting the M1 laptop, I have waited for almost two years for Fusion 13.  I would like to continue building machine images on Macs going forward, but if I need to pivot to another builder because there is not enough people on Macs using Packer with VMware, I understand.  Thank you again.

**Comment by tenthirtyam** [comment]
Can you try setting / adding / changing:

```hcl
disk_adapter_type    = "nvme"
network_adapter_type = "vmxnet3"
version              = 20
```

and then include the following `vmx_data`:

```
vmx_data = {
    "svga.autodetect" = true
    "usb_xhci.present" = true
  }
```
> **Note**
> `usb_xhci.present` is required in arm64 vms for Mouse and Keyboard support

**Comment by tenthirtyam** [comment]
> Can you try setting / adding / changing:
> 
> ```terraform
> disk_adapter_type    = "nvme"
> network_adapter_type = "vmxnet3"
> version              = 20
> ```
> 
> and then include the following `vmx_data`:
> 
> ```
> vmx_data = {
>     "svga.autodetect" = true
>     "usb_xhci.present" = true
>   }
> ```
> 
>  > Note
> > `usb_xhci.present` is required in arm64 vms for Mouse and Keyboard support

Any update @yhuang?

**Comment by tenthirtyam** [comment]
> > Can you try setting / adding / changing:
> > ```terraform
> > disk_adapter_type    = "nvme"
> > network_adapter_type = "vmxnet3"
> > version              = 20
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then include the following `vmx_data`:
> > ```
> > vmx_data = {
> >     "svga.autodetect" = true
> >     "usb_xhci.present" = true
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Note
> > > `usb_xhci.present` is required in arm64 vms for Mouse and Keyboard support

Any update @yhuang?
