### ISSUE TITLE
OVA not compatible with Terraform Provider for vSphere

### ISSUE THREAD

**Issue by dpottratz** [hashicorp/packer-plugin-vmware#120]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Using terraform "Deploying Virtual Machines from OVF/OVA" to create a virtual machine with and image created from packer will fail. 

#### Reproduction Steps

1. Create OVA/OVF image using packer.  Image is based on Ubuntu 18.04 VMware cloud image.  "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova"
3. Use [Deploying Virtual Machines from OVF/OVA](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#deploying-virtual-machines-from-ovfova) to deploy the image using "## Deployment of VM from Local OVF" 

It fails with the follow error:
│ Error: error while importing ovf/ova template, A specified parameter was not correct: ovfSection.info.key
│
│   with vsphere_virtual_machine.cvuv_vm,
│   on main.tf line 65, in resource "vsphere_virtual_machine" "vm":
│   65: resource "vsphere_virtual_machine" "vm" {
│

With the Ubuntu Cloud image from "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova"  Terraform will import the image without any issues. 

It seems like packer is writing the OVF XML incorrectly.  When using the 'disk' information from the packer OVF (because the information has changed with changes to the disk) and inserting it into the Ubuntu OVF XML the image will import without any issues. 

### Packer version

From `packer version` 
v1.7.10

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by tenthirtyam** [comment]
> Can we please get this issue fix? Seems like an issue with govmomi codebase not allowing to import the ovf/ova
> 
> https://issuehint.com/issue/vmware/govmomi/2666

@GlasgowMoe - if this is an issue with `vmware/govmomi`, the issue should be raised upstream.

**Comment by tenthirtyam** [comment]
Please refer to https://github.com/vmware/govmomi/issues/2666. This is the issue link on the upstream dependency.

**Comment by tenthirtyam** [comment]
Closing per https://github.com/hashicorp/packer-plugin-vmware/issues/120#issuecomment-1452626775. Please follow the upstream issue.
