### ISSUE TITLE
Support for NTP

### ISSUE THREAD

**Issue by modem7** [hashicorp/packer-plugin-vmware#127]
#### Description

Allow the ability to enable open-vmware-tools time sync.

![image](https://user-images.githubusercontent.com/4349962/227918783-82040dbc-8e0c-42b4-998f-18e3c5adcb52.png)

#### Use Case(s)

In cases where the VM/Hypervisor is going into a airgapped environment, being able to allow the guest to synchronise time is very useful.

**Comment by tenthirtyam** [comment]
This can be accomplished at provisioning time with the Terraform provider for vSphere.
