### ISSUE TITLE
Update plugin to support Fusion 13 by default

### ISSUE THREAD

**Issue by nywilken** [hashicorp/packer-plugin-vmware#131]
Please search the existing issues for relevant feature requests, and use the
reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

As called out by a number of issues getting this plugin to work with Fusion 13 on M1/M2-based
chipsets for ARM based OSes requires a bit of additional configuration changes. 

There has been some work to update this plugin for installing VMware tools but the driver refers to 
Fusion v6 and the generated vmx file contains lsilogic settings, which are not supported in Fusion 13. 

This issue is proposing the following:
 - Create a new driver specifically for Fusion 13
 - Update the generated vmx file to work with latest versions of VMware by default; drop lsilogic support.
 - Mark EOL VMware versions as unsupported. 

#### Use Case(s)
 - https://github.com/hashicorp/packer-plugin-vmware/issues/108
 - https://github.com/hashicorp/packer-plugin-vmware/issues/45
 - https://github.com/hashicorp/packer-plugin-vmware/issues/52

**Comment by tenthirtyam** [comment]
😶‍🌫️ Should also include Workstation 17 (Windows and Linux).

**Comment by tenthirtyam** [comment]
In progress.

**Comment by tenthirtyam** [comment]
Suggesting the following:

Short-term:
- Support VMware ESXi 7.0 and 8.0, per Broadcom product lifecycle.
- Support VMware Fusion 13 for macOS, per Broadcom product lifecycle.
  - amd64 (Intel)
  - arm64 (Apple Silicon)
- Support VMware Workstation 17 for Windows, per Broadcom product lifecycle.
  - amd64
  - consolidate versioned drivers
- Support VMware Workstation 17 for Linux, per Broadcom product lifecycle.
  - amd64
  - consolidate versioned drivers
- Remove Support for VMware Workstation Player for Windows, per 2024 changes to VMware Workstation.
- Remove Support for VMware Workstation Player for Linux, per 2024 changes to VMware Workstation.

Long-term:
- Remove Support for VMware ESXi
  - In favor of `packer-plugin-vsphere`. VMware vSphere Hypervisor ("Free ESXi") is no longer available.
