### ISSUE TITLE
Packer understands relative ISO paths, VMware doesn't

### ISSUE THREAD

**Issue by stephenreay** [hashicorp/packer-plugin-vmware#25]
#### Overview of the Issue

A previously working Packer config suddenly failed to boot VMWare (using Fusion 12) machines properly - the ISO was set, but never "Connected", and the VM shows "No Operating System found".

Some comparison with a manually-created VM shows that the path for the ISO was absolute.

The only change I've made in the Packer config, was to define the `iso_target_path` property (I'd previously used an external step to download the ISOs for repeated use). It seems that when this path is relative, Packer understands it fine, but VMWare does not.

The work-around for now is to supply the path as absolute, but ideally Packer would handle this.

#### Reproduction Steps

Have a packer config with `iso_target_path` specified as a relative path.

### Plugin and Packer version

1.712

### Operating system and Environment details

macOS 11.4 on Intel.

VMWare Fusion Professional 12.1.2

**Comment by puetzk** [comment]
Actually, it's a worse than that - config.VMXTemplatePath is https://www.packer.io/docs/builders/vmware/iso#vmx_template_path - it's an input template file, not the .vmx we're going to write, which is https://github.com/hashicorp/packer-plugin-vmware/blob/274f4049159f7ada33bd0742c72c0ef27fee59d7/builder/vmware/iso/step_create_vmx.go#L335
much later in the function. So in addition to everything being invalid relative paths, it's completely the wrong thing.

**Comment by TigerC10** [comment]
I am eagerly awaiting a fix.

**Comment by tenthirtyam** [comment]
Addressed in #247.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom
