### ISSUE TITLE
maxSnapshots

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vmware#32]
_This issue was originally opened by @Man-Yee in https://github.com/hashicorp/packer/issues/11139 and has been migrated to this repository. The original issue description is below._

---

I would like to disable snapshot in vmware.

I know that I can set this advanced configuration (snapshot.maxSnapshots) to "0" to achieve this.

I also know that if I modify the .ovf file with the following line, it will achieve the wanted result:

```
<VirtualHardwareSection ovf:transport="com.vmware.guestInfo"> <Info>Virtual hardware requirements</Info> . . . <vmw:ExtraConfig ovf:required="false" vmw:key="snapshot.maxSnapshots" vmw:value="0"/> </VirtualHardwareSection>
```

I would like to automate this. According to documentation, I can possibly use extraConfig in configure_parameters.

I tried many variations in my .hcl file , but without success:

```
configuration_parameters = { extraConfig = { key = "snapshot.maxSnapshots" value = "0" } }
```

It complains about
Inappropriate value for attribute "configuration_parameters": element "extraConfig": string required.

Then I tried this:

```
configuration_parameters = { "extraConfig" = "snapshot.maxSnapshots=0" }
```

Although the build pass, deploying the .ova file does not yield the wanted result.

What is the correct format to use extraConfig? Is `snapshot.maxSnapshots` supported?

**Comment by tenthirtyam** [comment]
For general questions, we recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for greater visibility.  The GitHub issue tracker is only watched by a small group of maintainers and collaborators and is typically reserved for bug reports and enhancement request. You will typically have more success finding assistance on the forum.

If you find the forum to be more helpful or if you've found the answer to your question elsewhere, please comment and close the issue. If there is no further activity on this question within the next 30 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
