### ISSUE TITLE
Packer vmware-iso builder incorrectly setting cpus value

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vmware#34]
_This issue was originally opened by @kenleexyz in https://github.com/hashicorp/packer/issues/11231 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

`vmware-iso` builder appears to be incorrectly dividing the `cpus` option value by the `cores` / `cpuid.coresPerSocket` option value.

#### Reproduction Steps

1. Create a template which uses the `vmware-iso` builder.
2. Set `cpus` option to `1`.
3. Set `cores` option to `2`.
4. Inititate Packer build.
5. In VMware Workstation, open the VM settings pane for the Packer VM and observe under 'Processors' that the number of processors / CPU sockets is `Invalid: 0.5` (expect `1`).

Same behaviour observed when `cpus` set to `2`, `cores` set to `2`. VMware shows number of processors as `1` (expect `2`).

Same behaviour when using `cpuid.coresPerSocket` option under `vmx_data`.

![image](https://user-images.githubusercontent.com/44574715/131360002-01844549-fc57-4759-b07b-16f50504c014.png)

### Packer version

Packer v1.7.4

### Simplified Packer Buildfile

``` hcl
source "vmware-iso" "ubuntu-amd64" {
  // Hardware resources
  cpus                    = 1
  cores                   = 2
  disk_size               = 32768
  disk_adapter_type       = "scsi"
  memory                  = 2048
  network                 = "NAT"

  // Communicator settings
  communicator            = "ssh"
  ssh_handshake_attempts  = 50
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_timeout             = "10m"
  ssh_username            = "vagrant"

  // Guest OS settings
  guest_os_type           = "ubuntu-64"
  shutdown_command        = "echo 'vagrant' | sudo -S shutdown -P now"
  tools_upload_flavor     = "linux"
}

build {
  source "source.vmware-iso.ubuntu-amd64" {
    name                = "ubuntu-20-04"
    boot_command        = [" <wait>"," <wait>"," <wait>"," <wait>"," <wait>","<esc><wait>","<f6><wait>","<esc><wait>","<bs><bs><bs><bs><wait>"," autoinstall<wait5>"," ds=nocloud-net<wait5>",";s=http://<wait5>{{.HTTPIP}}<wait5>:{{.HTTPPort}}/<wait5>"," ---<wait5>","<enter><wait5>"]
    boot_wait           = "5s"
    iso_url             = "https://releases.ubuntu.com/20.04.2/ubuntu-20.04.2-live-server-amd64.iso"
    iso_checksum        = "sha256:d1f2bf834bbe9bb43faf16f9be992a6f3935e65be0edece1dee2aa6eb1767423"
    http_directory      = "resources/http"
  }

  post-processor "vagrant" {
    output              = "my.box"
  }
}
```

### Operating system and Environment details

Windows 10 20H2 (Build 19042.1165)
VMware Workstation Pro 16.1.2 (Build 17966106)

**Comment by tenthirtyam** [comment]
This is correct and is also seen in a the `packer-plugin-vsphere` and `terraform-provider-vsphere`.

`cores` (per socket) is the number of cores per socket in the virtual machine.

`cpus` is the total number of virtual processor cores to assign to the virtual machine.

The number of vCPUs on the virtual machine will be `cpus` divided by `cores`. The value supplied to `cpus` must be evenly divisible by `cores`.

The value of the COU sockets is determined by dividing the number of CPUs by the number of cores per socke

Hence, 1cpu / 2cores = 0.5 sockets (invalid).

But 2 cpus / 1 core = 2 sockets

Or 8 cpus / 2 cores = 4 sockets 

Or 8 cpus / 4 cores = 2 sockets

Or 8 cpus / 8 cores = 1 socket.


Recommend: `docs`


**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Marking this issue as closed.

If you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thank you!
