### ISSUE TITLE
`vmware-iso`: download of existing uploaded ISO

### ISSUE THREAD

**Issue by Pollux42** [hashicorp/packer-plugin-vmware#38]
#### Description

The feature that I request is actually already done for the vsphere plugin.
Is it possible to replicate what has been done in [this issue](https://github.com/hashicorp/packer/issues/9951) but for the vmware-iso plugin?

**Comment by tenthirtyam** [comment]
@Pollux42 -

I do not see this issue in `vmware-iso` >= v1.0.3 on subsequent builds.

```hcl
packer {
  required_version = ">= 1.7.8"
  required_plugins {
    vmware = {
      version = ">= v1.0.3"
      source  = "github.com/hashicorp/vmware"
    }
    vagrant = {
      version = ">= v1.0.0"
      source  = "github.com/hashicorp/vagrant"
    }
  }
}
```

Results:

```bash
> make build-vmware-iso.vagrant-vmw
> Initializing plug-ins...
packer init -only=vmware-iso.vagrant-vmw -var-file=photon-4.0.pkrvars.hcl .
> Validating builder: vmware-iso.vagrant-vmw.
packer validate -only=vmware-iso.vagrant-vmw -var-file=photon-4.0.pkrvars.hcl .
The configuration is valid.
Building with builder: vmware-iso.vagrant-vmw.
packer build --force -only=vmware-iso.vagrant-vmw -var-file=photon-4.0.pkrvars.hcl .
vmware-iso.vagrant-vmw: output will be in this color.

==> vmware-iso.vagrant-vmw: Retrieving ISO
==> vmware-iso.vagrant-vmw: Trying https://packages.vmware.com/photon/4.0/Rev1/iso/photon-4.0-ca7c9e933.iso
==> vmware-iso.vagrant-vmw: Trying https://packages.vmware.com/photon/4.0/Rev1/iso/photon-4.0-ca7c9e933.iso?checksum=sha1%3Abec6359661b43ff15ac02b037f8028ae116dadb3
==> vmware-iso.vagrant-vmw: https://packages.vmware.com/photon/4.0/Rev1/iso/photon-4.0-ca7c9e933.iso?checksum=sha1%3Abec6359661b43ff15ac02b037f8028ae116dadb3 => /Users/johnsonryan/photon-packer-templates/packer_cache/3dffc38b4004af77f120964e5c148c676180c975.iso
==> vmware-iso.vagrant-vmw: Configuring output and export directories...
==> vmware-iso.vagrant-vmw: Creating required virtual machine disks
==> vmware-iso.vagrant-vmw: Building and writing VMX file
==> vmware-iso.vagrant-vmw: Starting HTTP server on port 8944
==> vmware-iso.vagrant-vmw: Starting virtual machine...
==> vmware-iso.vagrant-vmw: Connecting to VNC...
==> vmware-iso.vagrant-vmw: Waiting 3s for boot...
==> vmware-iso.vagrant-vmw: Typing the boot command over VNC...
```

In the above, you can see that it detects the image is already available in the `packer_cache` directory.

```bash
==> vmware-iso.vagrant-vmw: https://packages.vmware.com/photon/4.0/Rev1/iso/photon-4.0-ca7c9e933.iso?checksum=sha1%3Abec6359661b43ff15ac02b037f8028ae116dadb3 => /Users/johnsonryan/photon-packer-templates/packer_cache/3dffc38b4004af77f120964e5c148c676180c975.iso
```

Regards,
Ryan
@tenthirtyam

**Comment by Pollux42** [comment]
Thank you for your response.
The issue is only when you use a [remote VMware hypervisor](https://www.packer.io/docs/builders/vmware/iso#building-on-a-remote-vsphere-hypervisor). There are two steps for putting the iso at the right place.
1. First download the iso locally on the host that runs packer.
2. Then upload the iso from the host that runs packer to the remote VMware hypervisor.

In the case where the iso is not present locally (on the host that runs packer) but is already present on the VMware hypervisor, packer should realize that the correct file is present on the remote host before/instead of downloading it locally.

**Comment by tenthirtyam** [comment]
Thanks for clarifying the enhacnement.

Ryan

**Comment by tenthirtyam** [comment]
With the release of Packer Plugin for VMware [ v1.1.0](https://github.com/hashicorp/packer-plugin-vmware/releases/tag/v1.1.0), support for VMware vSphere Hypervisor (ESXi) is deprecated and will be removed in a future release. Please transition to using the [Packer Plugin for VMware vSphere](https://developer.hashicorp.com/packer/integrations/hashicorp/vsphere). The project will continue to provide bug fixes; however, enhancements for this platform will no longer be addressed.
