### ISSUE TITLE
Can we get a new tag of this repo?

### ISSUE THREAD

**Issue by tzneal** [hashicorp/packer-plugin-vmware#47]
I built packer using the main branch of this and it resolves the ISO exported to OVF issue that I'm experiencing.  I  was going to submit a PR against the main packer repo to update this dependency, but there's no tag here to reference.

**Comment by tenthirtyam** [comment]
Shipped in [v1.0.5](https://github.com/hashicorp/packer-plugin-vmware/releases/tag/v1.0.5).

cc @nywilken 


**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
