### ISSUE TITLE
`vmware-vmx`: does not find HostIP if network type is being changed

### ISSUE THREAD

**Issue by puetzk** [hashicorp/packer-plugin-vmware#54]
#### Overview of the Issue

If a packer vmware-vmx template is changing the ethernet0.connectionType from its source image in `vmx_data`, packer fails to correctly determine the HostIP.

This seems to be because it retreives the network name from the StateBag
https://github.com/hashicorp/packer-plugin-vmware/blob/310364cb46ffa330e0400bac3ea273667888c0d9/builder/vmware/common/driver.go#L578

where it was set during cloning
https://github.com/hashicorp/packer-plugin-vmware/blob/310364cb46ffa330e0400bac3ea273667888c0d9/builder/vmware/vmx/step_clone_vmx.go#L121

And therefore does not notice if StepConfigureVMX made any changes later before the image launched (e.g. using [`vmx_data`](https://www.packer.io/docs/builders/vmware/vmx#vmx_data))

#### Reproduction Steps

Start with a base .vmx that is using e.g. Bridged networking (I had used ovftool.exe to import http://cloud-images-archive.ubuntu.com/releases/focal/release-20210315/ubuntu-20.04-server-cloudimg-amd64.ova

ovftool ubuntu-20.04-server-cloudimg-amd64.ova testin\test.vmx

This creates test.vmx with `ethernet0.connectionType = "bridged"`.

packer build -debug test.pkr.hcl (template has `vmx_data = { "ethernet0.connectionType" = "nat" }`)</summary>

Build fails with 

> ==> vmware-vmx.vmware: Cloning source VM...
> ==> vmware-vmx.vmware: Pausing after run of step 'StepCloneVMX'. Press enter to continue.
> ==> vmware-vmx.vmware: Pausing after run of step 'StepConfigureVMX'. Press enter to continue.
> ==> vmware-vmx.vmware: Pausing after run of step 'StepSuppressMessages'. Press enter to continue.
> ==> vmware-vmx.vmware: Error detecting host IP: Unable to find host IP from devices [vmnet0], last error: No host declarations containing vmnet0 found

The same error would of course also affect [PotentialGuestIP](https://github.com/hashicorp/packer-plugin-vmware/blob/310364cb46ffa330e0400bac3ea273667888c0d9/builder/vmware/common/driver.go#L320) and [HostAddress](https://github.com/hashicorp/packer-plugin-vmware/blob/310364cb46ffa330e0400bac3ea273667888c0d9/builder/vmware/common/driver.go#L499), but HostIP fails first.

I would have said that the initialization of `state.Put("vmnetwork", networkType)` should just be done slightly later, after StepConfigurVMX has run, but there is very specifically a test to make sure StepCloneVMX sets it. 
https://github.com/hashicorp/packer-plugin-vmware/blob/310364cb46ffa330e0400bac3ea273667888c0d9/builder/vmware/vmx/step_clone_vmx_test.go#L98-L100

Obviously tests can be changed, but it makes me unsure that this is the right way to proceed...

### Plugin and Packer version

Packer v1.7.8

### Simplified Packer Buildfile

<details>
<summary>test.pkr.hcl</summary>

```
source "vmware-vmx" "vmware" {
  communicator         = "ssh"
  headless             = "true"
  output_directory     = "testout"
  shutdown_command     = "shutdown -P now"
  source_path          = "testin/test.vmx"
  ssh_username         = "root"
  vm_name              = "test"
  vmx_data = {
    "bios.bootOrder"        = "hdd"
    "bios.hddOrder"         = "scsi0"
    "ide1:0.startConnected" = "TRUE"
    "rtc.diffFromUTC"       = "0"
    "ethernet0.connectionType" = "nat"
  }
}

build {
  sources = ["source.vmware-vmx.vmware"]

  provisioner "shell" {
    inline = [ "echo communicator works" ]
  }
}
```
</details>

### Operating system and Environment details

Windows 10 20H2, vmware 15.5.7

**Comment by tenthirtyam** [comment]
Marking this stale item as closed.

If this issue is still reproducible with the latest versions of Packer, the Packer Plugin for VMware, and Workstatiom, please open a new issue.
