### ISSUE TITLE
Add support for UEFI firmware and secure boot

### ISSUE THREAD

**Issue by arizvisa** [hashicorp/packer-plugin-vmware#58]
As the next generation of Windows OS will be requiring UEFI and likely TPM, it'd likely be a good idea and sync some of the PRs that were added to the vsphere-iso builder such as for "firmware", "nested", "force_bios_setup", etc.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

The next generation of Windows OS will require nested virtualization and efi-secure. These were introduced in the vsphere builders/plugins but was neglected to also be added to the vmware builders/plugins. This should be as simple as adding the relevant vmx configurations to step_create_vmx.go.

I'll add more details as I encounter them as I'm still waiting on licenses for testing this shit out.

As an example of what to add to step_create_vmx.go
```
firmware = "{{ .firmware }}"
vhv.enable = "{{ .nested }}"
```

#### Use Case(s)

Windows 11 System Requirements

#### Potential configuration

```
"firmware": "efi-secure"
"nested": true
"force_bios_setup": false
```

**Comment by tenthirtyam** [comment]
### Notes for Implementation

**BIOS**:

```text
firmware = "bios"
```

- or left blank (expection is Apple Silicon).

**UEFI**:

```text
firmware = "efi"
```

- or

```text
firmware = "efi"
uefi.secureBoot.enabled = "FALSE"
```

- On Apple Silicon, `efi` is always the default, not `bios`.

**UEFI Secure Boot**:

```text
firmware = "efi"
uefi.secureBoot.enabled = "TRUE"
```

Follow the same options used in `vsphere-iso`.

`firmware`:
- `bios`
- `efi`
- `efi-secure`

**Comment by tenthirtyam** [comment]
Code completed and in testing.
