### ISSUE TITLE
I can replicate issue 6689

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vmware#61]
_This issue was originally opened by @ZeroChaos- in https://github.com/hashicorp/packer/issues/11450 and has been migrated to this repository. The original issue description is below._

---
identical bug to https://github.com/hashicorp/packer/issues/6689

I have ipv6 disabled as suggested in the bug, vmware 16.1.0, packer 1.7.8, kernel 5.15.5

netstat -an only shows http server listening on tcp6

**Comment by ZeroChaos-** [comment]
I can no longer replicate the issue, please close this bug.

**Comment by tenthirtyam** [comment]
cc @nywilken for closure.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
