### ISSUE TITLE
Can't use cd_files variable to send preseed with debian

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-vmware#64]
_This issue was originally opened by @ZeikoFr in https://github.com/hashicorp/packer/issues/11525 and has been migrated to this repository. The original issue description is below._

---
Hi,

Not 100% sure if it's a packer issue or a lack of knowledge of my part, if it is my apologies.

#### Overview of the Issue

Using cd_files to create an iso containing a preseed file to auto install debian whiteout needing http server.

Packer properly create the iso and the second cd drive needed but when debian installer launch the preseed iso is on /dev/sr1 and it is not accessible because it's not mounted. 
/cdrom is used by debian installer
Afaik you cannot mount anything else during automated setup until you get to the preseed part.

#### Reproduction Steps

Create a packer template with cd_files for debian
Installer will run until it can't found the preseed file because it does not auto mount /dev/sr1

### Packer version

1.7.8

### Simplified Packer Template
```
source "vmware-iso" "Debian-11.1-Template" {
  boot_command     = ["e<down><down><down><end>priority=critical auto=true file=/dev/sr1/preseed.cfg preseed-md5=5c7bd38f2916a9c8caf7a57899a688a3<leftCtrlOn>x<leftCtrlOff>"]
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  cd_files = ["./http/debian/preseed.cfg"]
  cd_label = "cidata"
  }
```

### Operating system and Environment details

I tried on vmware workstation and vmware vSphere from manjaro and ubuntu using the same version of packer

Got the exact same problem on both 

### Log Fragments and crash.log files

```
vmware-iso.Debian-11-Template: output will be in this color.

==> vmware-iso.Debian-11-Template: Trying https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso
==> vmware-iso.Debian-11-Template: Trying https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso?checksum=sha256%3A8488abc1361590ee7a3c9b00ec059b29dfb1da40f8ba4adf293c7a30fa943eb2
2022/01/25 20:19:26 packer-builder-vmware-iso plugin: Leaving retrieve loop for ISO
2022/01/25 20:19:26 packer-builder-vmware-iso plugin: No floppy files specified. Floppy disk will not be made.
2022/01/25 20:19:26 packer-builder-vmware-iso plugin: CD label is set to cidata
2022/01/25 20:19:26 packer-builder-vmware-iso plugin: CD path: /tmp/packer2545184248.iso
==> vmware-iso.Debian-11-Template: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso?checksum=sha256%3A8488abc1361590ee7a3c9b00ec059b29dfb1da40f8ba4adf293c7a30fa943eb2 => /home/zeiko/.cache/packer/bed3360a8849258231657d615579999ba9f47fc6.iso
2022/01/25 20:19:26 packer-builder-vmware-iso plugin: Wrote 7430 bytes to preseed.cfg
2022/01/25 20:19:26 packer-builder-vmware-iso plugin: Executing: /usr/bin/mkisofs [-joliet -volid cidata -o /tmp/packer2545184248.iso /tmp/packer_to_cdrom898500605]
==> vmware-iso.Debian-11-Template: Configuring output and export directories...
==> vmware-iso.Debian-11-Template: Creating CD disk...
    vmware-iso.Debian-11-Template: Warning: creating filesystem with (nonstandard) Joliet extensions
    vmware-iso.Debian-11-Template: but without (standard) Rock Ridge extensions.
    vmware-iso.Debian-11-Template: It is highly recommended to add Rock Ridge
    vmware-iso.Debian-11-Template: Setting input-charset to 'UTF-8' from locale.
    vmware-iso.Debian-11-Template: Total translation table size: 0
    vmware-iso.Debian-11-Template: Total rockridge attributes bytes: 0
    vmware-iso.Debian-11-Template: Total directory bytes: 0
    vmware-iso.Debian-11-Template: Path table size(bytes): 10
    vmware-iso.Debian-11-Template: Max brk space used 0
    vmware-iso.Debian-11-Template: 184 extents written (0 MB)
    vmware-iso.Debian-11-Template: Done copying paths from CD_dirs
```

**Comment by tenthirtyam** [comment]
```
file=/dev/sr1:preseed.cfg
```

**Comment by Mihail-blip** [comment]
I've got the same issue with debian 11.3 on hyper-V machines. I am using mkisofs for iso creation.

**Comment by Mihail-blip** [comment]
I've been working on this issue for a couple of days already.
Looks like debian installer doesn't mount other cdroms by default (expect for installation media cdrom). You have to tell it to mount it separately. 
There is a way to cheat it through *boot_command*, where you invoke a shell command just after the *grub boot* command. At first there will be a popup error claiming preseed file could not be retrieved, you then open the shell console, mount the 2nd virtual cdrom and tell it to retry loading preseed file.

Here is the boot code I used, it worked for me on Hyper-V for debian 11.3, I expect it to work on VMware as well.
`boot_command= [
  "c<wait>",
  "linux /install.amd/vmlinuz",
  " auto-install/enable=true",
  " debconf/priority=critical",
  " preseed/file=/mnt/cdrom2/preseed.cfg<enter><wait>",
  "initrd /install.amd/initrd.gz<enter><wait>",
  "boot<enter><wait>",
  "<leftAltOn><f2><leftAltOff>",
  "<enter><wait>",
  "mkdir /mnt/cdrom2<enter>",
  "mount /dev/sr1 /mnt/cdrom2<enter>",
  "<leftAltOn><f1><leftAltOff>",
  "<enter><wait><enter>",
  "<down><down><down><down><enter>"
]`

After mounting the cdrom and getting the preseed file, I also had to unmount it, otherwise package manager will attempt to scan it for additional packages and pause the install process.
Just add this one line to your preseed :

`d-i preseed/early_command string umount /mnt/cdrom2 && echo 1 > /sys/block/sr1/device/delete`

I found the solution on a reddit post [here](https://www.reddit.com/r/debian/comments/sizzg4/mount_a_second_cdrom_with_preseed_during/).
Hope this helps. Take care.

**Comment by ZeikoFr** [comment]
> 

Damn I completely forget about this issue, we finally manage that differently, packer create template on a dedicated isolated network where it get the preseed securely and then push the template to a shared library.

I did not managed at the time to make it work properly with the boot command I the reddit post (I'm the OP lol) but it's been a while so I might tried that again.

I think we can close the issue for now, thanks again !

**Comment by tenthirtyam** [comment]
cc @nywilken for closure.


**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by nywilken** [comment]
Thanks @ZeikoFr @tenthirtyam. Closing the issue as requested.

**Comment by theblop** [comment]
For those who struggled as much as I did to piece together everything needed to properly preseed debian from a cdrom image with packer, here is the final packer source I used for `debian-11.5.0-amd64-netinst.iso`:
```
locals {
  debian_preseed = file("${path.root}/templates/debian/preseed.cfg")
}
source "proxmox-iso" "debian" {
    additional_iso_files {
      iso_storage_pool = "local"
      unmount = true
      cd_label = "cidata"
      cd_content = {
        "/preseed.cfg" = local.debian_preseed
      }
  }
  boot_command =  [
    "<esc><wait>install <wait>auto=true priority=critical file=/mnt/cdrom2/preseed.cfg<wait>",
    " preseed-md5=<wait>", md5(local.debian_preseed), "<wait><enter><wait5>",
    "<leftAltOn><f2><leftAltOff>",
    "<wait><enter><wait>",
    "mkdir /mnt/cdrom2<enter>",
    "mount /dev/sr1 /mnt/cdrom2<enter><wait>",
    "ls -l /mnt/cdrom2<enter><wait>",
    "<leftAltOn><f1><leftAltOff><wait>",
    "<enter><wait><enter><wait>",
    "<down><down><down><down><enter>",
  ]
...
}
```

**Comment by xavierpioche** [comment]
you can also use the debian menu by selecting automated install then mount the cdrom and type the path.
```
vm_boot_command = [
      "<wait>",
      "<down><down><enter>",
      "<down><down><down><down><down><enter>",
      "<wait30s>",
      "<leftAltOn><f2><leftAltOff>",
      "<enter><wait>",
      "mount /dev/sr1 /media<enter>",
      "<leftAltOn><f1><leftAltOff>",
      "file:///media/ks.cfg",
      "<enter><wait>"
  ]

```

**Comment by badges7** [comment]
> _This issue was originally opened by @ZeikoFr in [hashicorp/packer#11525](https://github.com/hashicorp/packer/issues/11525) and has been migrated to this repository. The original issue description is below._
> 
> Hi,
> 
> Not 100% sure if it's a packer issue or a lack of knowledge of my part, if it is my apologies.
> 
> #### Overview of the Issue
> Using cd_files to create an iso containing a preseed file to auto install debian whiteout needing http server.
> 
> Packer properly create the iso and the second cd drive needed but when debian installer launch the preseed iso is on /dev/sr1 and it is not accessible because it's not mounted. /cdrom is used by debian installer Afaik you cannot mount anything else during automated setup until you get to the preseed part.
> 
> #### Reproduction Steps
> Create a packer template with cd_files for debian Installer will run until it can't found the preseed file because it does not auto mount /dev/sr1
> 
> ### Packer version
> 1.7.8
> 
> ### Simplified Packer Template
> ```
> source "vmware-iso" "Debian-11.1-Template" {
>   boot_command     = ["e<down><down><down><end>priority=critical auto=true file=/dev/sr1/preseed.cfg preseed-md5=5c7bd38f2916a9c8caf7a57899a688a3<leftCtrlOn>x<leftCtrlOff>"]
>   iso_checksum     = "${var.iso_checksum}"
>   iso_url          = "${var.iso_url}"
>   cd_files = ["./http/debian/preseed.cfg"]
>   cd_label = "cidata"
>   }
> ```
> 
> ### Operating system and Environment details
> I tried on vmware workstation and vmware vSphere from manjaro and ubuntu using the same version of packer
> 
> Got the exact same problem on both
> 
> ### Log Fragments and crash.log files
> ```
> vmware-iso.Debian-11-Template: output will be in this color.
> 
> ==> vmware-iso.Debian-11-Template: Trying https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso
> ==> vmware-iso.Debian-11-Template: Trying https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso?checksum=sha256%3A8488abc1361590ee7a3c9b00ec059b29dfb1da40f8ba4adf293c7a30fa943eb2
> 2022/01/25 20:19:26 packer-builder-vmware-iso plugin: Leaving retrieve loop for ISO
> 2022/01/25 20:19:26 packer-builder-vmware-iso plugin: No floppy files specified. Floppy disk will not be made.
> 2022/01/25 20:19:26 packer-builder-vmware-iso plugin: CD label is set to cidata
> 2022/01/25 20:19:26 packer-builder-vmware-iso plugin: CD path: /tmp/packer2545184248.iso
> ==> vmware-iso.Debian-11-Template: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso?checksum=sha256%3A8488abc1361590ee7a3c9b00ec059b29dfb1da40f8ba4adf293c7a30fa943eb2 => /home/zeiko/.cache/packer/bed3360a8849258231657d615579999ba9f47fc6.iso
> 2022/01/25 20:19:26 packer-builder-vmware-iso plugin: Wrote 7430 bytes to preseed.cfg
> 2022/01/25 20:19:26 packer-builder-vmware-iso plugin: Executing: /usr/bin/mkisofs [-joliet -volid cidata -o /tmp/packer2545184248.iso /tmp/packer_to_cdrom898500605]
> ==> vmware-iso.Debian-11-Template: Configuring output and export directories...
> ==> vmware-iso.Debian-11-Template: Creating CD disk...
>     vmware-iso.Debian-11-Template: Warning: creating filesystem with (nonstandard) Joliet extensions
>     vmware-iso.Debian-11-Template: but without (standard) Rock Ridge extensions.
>     vmware-iso.Debian-11-Template: It is highly recommended to add Rock Ridge
>     vmware-iso.Debian-11-Template: Setting input-charset to 'UTF-8' from locale.
>     vmware-iso.Debian-11-Template: Total translation table size: 0
>     vmware-iso.Debian-11-Template: Total rockridge attributes bytes: 0
>     vmware-iso.Debian-11-Template: Total directory bytes: 0
>     vmware-iso.Debian-11-Template: Path table size(bytes): 10
>     vmware-iso.Debian-11-Template: Max brk space used 0
>     vmware-iso.Debian-11-Template: 184 extents written (0 MB)
>     vmware-iso.Debian-11-Template: Done copying paths from CD_dirs
> ```

**Comment by badges7** [comment]
Okey

**Comment by badges7** [comment]
Closed

**Comment by badges7** [comment]
Okey
