### ISSUE TITLE
VMware Workstation on Windows: "Incorrect path in network mappings"

### ISSUE THREAD

**Issue by lluked** [hashicorp/packer-plugin-vmware#65]
Windows 11
VMware® Workstation 16 Pro (16.2.2 build-19200509)
Packer v1.7.10
Plugin pulled today

When running packer build on a freshly setup system it fails with:

"Could not determine network mappings from files in path: C:/Program Files (x86)/VMware/VMware Workstation"

Workstation 16 Pro has installed network files in "C:\ProgramData\VMware", the missing file is netmap.conf. If netmap.conf is placed in the directory stated and not "C:\ProgramData\VMware" the build continues to fail with the same message. I only found this out after realising netmap.conf could be made by editing the network config with vmware and by chance Packer started working. 

Originally I was putting a copy of netmap.conf in the stated directory and packer still wouldn't work. After using the network editor and it working I then tested Packer with the file only in one location at a time and it would not work under "C:/Program Files (x86)/VMware/VMware Workstation" which is the stated directory in the message. I'm guessing there was a change in structure at some point for VMware and the error message was overlooked.

Thanks
Luke

**Comment by lluked** [comment]
> I am experiencing the same issue.
> 
> My setup:
> 
> - Windows 10, version 20H2
> 
> - VMware® Workstation 16 Pro (16.2.4 build-20089737)
> 
> - Packer v1.7.9
> 
> - Plugin pulled today
> 
> 
> 
> There seems to be a [work-around](https://www.vgemba.net/vmware/Packer-Workstation-Error/) for this (also posted to the [Packer community forums](https://discuss.hashicorp.com/t/solved-could-not-determine-network-mappings-on-vmware-iso-vmw-16-2-2/36265/2)), but I haven't tried it out yet.

Thanks, seems to be what I have mentioned but in more detail.

Kind Regards
Luke

**Comment by ChristoWolf** [comment]
I tried it, the mentioned [work-around](https://www.vgemba.net/vmware/Packer-Workstation-Error/) resolved the issue.

**Comment by tenthirtyam** [comment]
I'm addressing this issue in pull request #198.
