### ISSUE TITLE
Set RAM size for video card

### ISSUE THREAD

**Issue by jremerich** [hashicorp/packer-plugin-vmware#66]
Hi!

I generated an OVA format image of CentOS 8 Stream using an [ISO file](http://centos.ufes.br/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20220215-dvd1.iso), but when I run terraform to create the VM in ESXi 6.7 it returns an error message: `Invalid VM configuration. Reason: 'Invalid configuration for device '2'.' for property 'VirtualVideoCard.videoRamSizeInKB'`.

So I did some searchs and find a bug about the `videoRamSizeInKB` parameter: https://kb.vmware.com/s/article/65205

To confirm this I extracted the OVA file, opened the ovf file and found that the value is set to 262144KB (256MB).

Before this Stream image, I did an image of CentOS 8 'normal' and this one generated an ovf with value 131072KB (128MB)

Is the same computer and same script (I only changed the iso's URL and checksum).

I looked on [documentation](https://www.packer.io/plugins/builders/vmware/iso) and don't found how to set video ram size.

When I create VM manually using ISO on VMware Workstation it already sets video ram to 256MB and doesn't enable to change.

Is possible to change this parameter? There is any workarround?

Here my environment:
- Packer v1.7.10
- Ubuntu 20.04.3 LTS 64bits

Thanks!

**Comment by tenthirtyam** [comment]
The [`video_ram`](https://www.packer.io/plugins/builders/vsphere/vsphere-iso#video_ram) capability is only available in the vSphere plugin and it's builders.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
For general questions, we recommend reaching out to the [community forum](https://discuss.hashicorp.com/c/packer) for greater visibility.  The GitHub issue tracker is only watched by a small group of maintainers and collaborators and is typically reserved for bug reports and enhancement request. You will typically have more success finding assistance on the forum.

If you find the forum to be more helpful or if you've found the answer to your question elsewhere, please comment and close the issue. If there is no further activity on this question within the next 30 days it will be closed.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
