### ISSUE TITLE
`vmware-iso`: Using the `snapshot_name` option with ESXi, the VMX file does not refer the correct snapshot

### ISSUE THREAD

**Issue by julien-lang** [hashicorp/packer-plugin-vmware#68]
I use packer to generate virtual machines on ESXi.

I set a [snapshot_name](https://www.packer.io/plugins/builders/vmware/iso#snapshot_name) combined with `"keep_registered": true` and  `"skip_export": true`.

Packer succeed to create the Virtual Machine and the snapshot is created indeed but the VMX file does refer the snapshot:

  * Actual result:
    ```
    scsi0:0.filename = "disk.vmdk"
    ```

  * Expected result:
    ```
    scsi0:0.filename = "disk-000001.vmdk"
    ```

Related to #20

**Comment by julien-lang** [comment]
I think the error might come from the list of steps in the _builder/vmware/iso/builder.go_ file.

The `StepCreateSnapshot` is defined before the `StepUploadVMX` step. So if I understand the code correclty, This will override the VMDK filename in the VMX.

**Comment by tenthirtyam** [comment]
This was, in fact, the issue. I've opened a PR to address this in both builders and address some minor tech debt for this option.
