### ISSUE TITLE
cleanup_remote_cache flag unrecognized

### ISSUE THREAD

**Issue by edqallen** [hashicorp/packer-plugin-vmware#71]
#### Overview of the Issue

The `cleanup_remote_cache` flag is unrecognized.  This flag was presumably added approx. two years ago.

#### Reproduction Steps

Create a JSON configuration for packer that uses this flag with a `vmware-iso` builder.

### Plugin and Packer version

`Packer v.1.8.0`

### Simplified Packer Buildfile

```
{
  "builders": [{
    "type": "vsphere-iso",
    "cleanup_remote_cache": true,
....
  }],
  "provisioners": [{
    "type": "shell",
    "inline": [
      "sudo rm /etc/machine-id",
      "sudo touch /etc/machine-id",
      "echo 'Packer template build complete'"
    ]
  }]
}

```

### Operating system and Environment details

amd64, Ubuntu 18.04.6

### Log Fragments and crash.log files

```
Error: Failed to prepare build: "vsphere-iso"

1 error occurred:
        * unknown configuration key: '"cleanup_remote_cache"'

```

**Comment by OpaDopa** [comment]
Any idea?

**Comment by tenthirtyam** [comment]
Base on the description, this is not a bug but perhaps confusion between available plugins and builders.

This capability [was adde](https://github.com/hashicorp/packer-plugin-vmware/commit/68e4f1cf9b9720629f6e60118f394040b48251fc)d to **packer-plugin-vmware** (`vmware-iso`); however, the description notes that **packer-plugin-vsphere** (`vsphere-iso`) is used, where this is not a valid option.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
