### ISSUE TITLE
floppy_content not working on vmware builders

### ISSUE THREAD

**Issue by fjcuadrado** [hashicorp/packer-plugin-vmware#77]
Hi, recently I've discovered that the `floppy_content` statement doesn't work at all when used in conjunction with any of the vmware builders (vmware-iso or vmware-vmx) provided by this plugin.

#### Overview of the Issue

As the [packer vmware plugin documentation](https://www.packer.io/plugins/builders/vmware/iso#floppy-configuration) states, there are some statements to configure a floppy disk in the virtual machine that's built by packer. This floppy disk is really useful for unattended Windows installs.

However, when the `floppy_content` statement is used no floppy disk is created by packer neither attached to the virtual machine. Any of the other statements (`floppy_files` or `floppy_dirs`) work as expected.

#### Reproduction Steps

Create a packer template with `floppy_content`, packer will ignore that option and build the template without creating the corresponding floppy disk.

### Plugin and Packer version

packer 1.8.1
packer-plugin-vmware 1.0.7

### Simplified Packer Buildfile

The following packer template can be used to reproduce the issue:

```hcl
packer {
  required_version = "~> 1.8.1"

  required_plugins {
    vmware = {
      source = "github.com/hashicorp/vmware"
      version = ">= 1.0.0"
    }
  }
}

locals {
  alpine_base_url = "http://dl-cdn.alpinelinux.org/alpine/v3.16"
  alpine_iso_url  = "${local.alpine_base_url}/releases/x86_64/alpine-virt-3.16.0-x86_64.iso"
  alpine_iso_checksum_url = "${local.alpine_iso_url}.sha256"
  alpine_repository_url = "http://dl-cdn.alpinelinux.org/alpine/v3.16/main"
}

source "vmware-iso" "alpine" {
  iso_checksum = "file:${local.alpine_iso_checksum_url}"
  iso_url      = local.alpine_iso_url

  communicator = "none"
  headless     = false

  floppy_content = {
    "hello.txt" = "Hello world!"
  }

  boot_command = [
    "<wait5>",
    "root<enter>",
    "<wait>",
    "mount -t vfat /dev/fd0 /media/floppy<enter>",
    "<wait>",
    "cat /media/floppy/hello.txt<enter>",
    "<wait10>",
  ]
  boot_wait = "10s"
}

build {
  sources = ["vmware-iso.alpine"]
}
```

As you can see, this template is pretty simple. An alpine ISO is downloaded and a floppy must be created with a `hello.txt` file, at boot time the floppy disk is mounted and the `hello.txt` file is printed to stdout. 

### Operating system and Environment details

Debian 11.3
VMWare WS 16.2.3

### Log Fragments and crash.log files

```
==> vmware-iso.alpine: Trying http://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64/alpine-virt-3.16.0-x86_64.iso?checksum=sha256%3Aba8007f74f9b54fbae3b2520da577831b4834778a498d732f091260c61aa7ca1
2022/06/17 06:56:48 packer-plugin-vmware_v1.0.7_x5.0_linux_amd64 plugin: 2022/06/17 06:56:48 Leaving retrieve loop for ISO
2022/06/17 06:56:48 packer-plugin-vmware_v1.0.7_x5.0_linux_amd64 plugin: 2022/06/17 06:56:48 No floppy files specified. Floppy disk will not be made.
2022/06/17 06:56:48 packer-plugin-vmware_v1.0.7_x5.0_linux_amd64 plugin: 2022/06/17 06:56:48 No CD files specified. CD disk will not be made.
```

[Full log file](https://gist.github.com/fjcuadrado/ee54e78ac5f3ae7d129a8c83f7144e55)

**Comment by fjcuadrado** [comment]
This issue is really easy to fix, it seems that the `Content` parameter is missing when the `StepCreateFloppy` is called.

```patch
diff --git a/builder/vmware/iso/builder.go b/builder/vmware/iso/builder.go
index 951aaab..35f1550 100644
--- a/builder/vmware/iso/builder.go
+++ b/builder/vmware/iso/builder.go
@@ -73,6 +73,7 @@ func (b *Builder) Run(ctx context.Context, ui packersdk.Ui, hook packersdk.Hook)
                },
                &commonsteps.StepCreateFloppy{
                        Files:       b.config.FloppyConfig.FloppyFiles,
+                       Content:     b.config.FloppyConfig.FloppyContent,
                        Directories: b.config.FloppyConfig.FloppyDirectories,
                        Label:       b.config.FloppyConfig.FloppyLabel,
                },
diff --git a/builder/vmware/vmx/builder.go b/builder/vmware/vmx/builder.go
index 23aa21d..1de0d4d 100644
--- a/builder/vmware/vmx/builder.go
+++ b/builder/vmware/vmx/builder.go
@@ -70,6 +70,7 @@ func (b *Builder) Run(ctx context.Context, ui packersdk.Ui, hook packersdk.Hook)
                },
                &commonsteps.StepCreateFloppy{
                        Files:       b.config.FloppyConfig.FloppyFiles,
+                       Content:     b.config.FloppyConfig.FloppyContent,
                        Directories: b.config.FloppyConfig.FloppyDirectories,
                        Label:       b.config.FloppyConfig.FloppyLabel,
                },
```

**Comment by jtognazzi** [comment]
I which version of vmware-iso is this fix available ? 
I guess none as the latest release 1.0.7 is from before the bug was fix

**Comment by ggiesen** [comment]
I'm hitting this as well. Any chance of a new release so `floppy_content` can be made usable?

**Comment by tenthirtyam** [comment]
The fix commit was made on 2022-07-27; however the last release was 2022-06-12. The next release would include this fix.

There are a couple PRs that should (ideally) be reviewed and considered for merge before the next release. I can work with the maintainer to review these.

This release should also be tested with Fusion 13, Workstation 13, and ESXi 8 as these were recently released and earlier versions of Fusion/Workstation are end-of-support 2022-12-22 and ESXi 6.5/6.7 was end-of-support 2022-10-15.

cc @nywilken 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by ggiesen** [comment]
I ended up compiling the plugin manually and installed it and can confirm the fix works, although that's certainly not ideal.

**Comment by tenthirtyam** [comment]
Thanks for confirming that the commit resolves this issue. If you watch this GitHub repository you can be notified when the next version is released, which will include this fix.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
