### ISSUE TITLE
Add support for VMware Cloud Director (VCD) builder

### ISSUE THREAD

**Issue by bogi0704** [hashicorp/packer-plugin-vmware#86]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Description

I would very much like to use packer in our VMware Cloud Director (VCD) environment natively. I am aware that there is a vSphere-iso builder, but that is, imho, just a workaround and does not help tenants without access to the vSphere backend at all.

#### Use Case(s)

A VCD Packer builder would enable us to move heavily towards immutable infrastructure on our VCD environment. We already have years of experience doing that on public clouds like azure or gcp.

#### References

There are multiple references here and there and many people have tried to create a Packer builder in the past. See [#1824](https://github.com/hashicorp/packer/issues/1824) and [#3280](https://github.com/hashicorp/packer/issues/3280) for example. These are already pretty old and relied on a deprecated library. The new library would be [vmware/go-vcloud-director](https://github.com/vmware/go-vcloud-director), which is also used for the VCD Terraform provider and maintained by the same devs.
There has also been another [try](https://github.com/sansaid/packer-vcd-builder/issues) by a dev, but that did not go anywhere, since he did not manage to find a publicly available instance to test against. He was also stuck on this [issue](https://github.com/vmware/go-vcloud-director/issues/295) regarding the [go-vcloud-director](https://github.com/vmware/go-vcloud-director) library.

Let's see if this leads to anywhere :)

**Comment by nywilken** [comment]
Thanks for opening up this request. Given the Packer team's current priorities we wont be able to work on this any time soon. But we do prioritize pull-request reviews if a member of the community is open to contributing a builder for VCD.

Pinging @tenthirtyam for thoughts on the request.

**Comment by tenthirtyam** [comment]
Sounds like a good idea for a builder - also, some good community reactions 👍 so far. (_Assuming each are VCD users._)

Happy raise the concept with some of our internal teams next chance we meet. The other option is for a community working group to organize and develop the builder for the plugin.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by arogarth** [comment]
Would be nice 👍

**Comment by quentinlegay** [comment]
that would be great! I am also waiting for it

**Comment by butler54** [comment]
Just to add a comment w.r.t scope and some investigation. Console access would be very difficult to implement form what i've seen due to the use of a custom VMWare protocol.

support for a vcd-clone operation.

**Comment by ChiefGhostZero0x1** [comment]
- Look I'm all for doing as you ask however I have to be careful not to do something that will cause harm when misuse is going to happen.  I'm a 37 yr old ADHD  dog dad and I get high a lot. I just did so many things everyone told me not to do because it will xyz so I didn't listen and now I'm just trying to deal with my own anxiety and trauma.  I am just not in the mood to get Fu***d again for being oblivious to risks.  I'm going to do the next right thing k.  Thank god I did this and wasn't the type to steal or harm cuz that's not how I operate.  I have been trying to get help with this Crazy sh*t but no one listens to me cuz no one understands anything I said for the most part except online and then I might as well just hand out metaphorical guns cuz that's what... what is it you're after.. technology that is so not like the rest of everything I broke everything more times than I can count knowing that it is the most powerful tool I have ever seen..  ![image](https://user-images.githubusercontent.com/89703573/215168803-ab87cbf2-22c9-498d-b52b-35df861984d0.jpeg)

**Comment by ChiefGhostZero0x1** [comment]
support for a vcd-clone operation

**Comment by tenthirtyam** [comment]
### Community Reminder

1. Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
2. Please do not leave "+1", 👍, or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
3. If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by majosula** [comment]
Hello, Is there any progress, workaround?

**Comment by sva-mk** [comment]
Hey @tenthirtyam, a VMware Cloud Director integration for Packer would greatly benefit our workflow. Is there anything we can do to assist in the development of this feature?

**Comment by tenthirtyam** [comment]
No plans at this time; however, base on the collection 👍 reactions I'll provider this over to our (VMware) product management for consideration.

**Comment by sva-mk** [comment]
Thank you for your consideration! We're excited to see if Packer integration with VMware Cloud Director becomes a possibility. If any additional information or support is needed from our end, please don't hesitate to reach out. We'll look forward to any updates or progress on this request.

**Comment by ibeerens** [comment]
Here is an extra vote for Packer integration with VMware Cloud Director.

Regards,

Ivo Beerens

**Comment by rasperepodvipodvert** [comment]
👍

**Comment by rgryder** [comment]
Would also like to voice my support for this. I have spent some time attempting to deconstruct the protocol used for the Cloud Director console, as that is the primary blocker in my view; managed to get programmatic access of sorts by hosting a modified version of the default console application, but that is a bodge at best. The minified Javascript SDK is an absolute nightmare to weed through.

I think this is going to require an olive branch from VMware for information on how the (very obscure and poorly documented) console protocol works at the very least, or preferably adding support for programmatic console access directly through vCD without relying on a browser-based client application, which severely limits flexibility.

**Comment by aliaksandr-dabrytski-epam** [comment]
I would also like to vote for this enhancement.

Regards,
Alex D.

**Comment by tenthirtyam** [comment]
> #### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by eduardbulai** [comment]
This would be of great help!

**Comment by tenthirtyam** [comment]
Hello! 👋 

I wanted to update this communituy that this request has been redirect to product management in the VMware Cloud Foundation Division at Broadcom for consideration. Since this plugin is targeted for use with VMware desktop hypervisors, Workstation and Fusion, this needs to be considered for a seperate plugin based on product directions.

Please provide your upvotes and comments on request [VCF-I-1741](https://vcf.ideas.aha.io/ideas/VCF-I-1741).

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom
