### ISSUE TITLE
Looking for guidance on dry builds with the ISO builder

### ISSUE THREAD

**Issue by Shocktrooper** [hashicorp/packer-plugin-vmware#94]
I was building with the ISO builder and tried to use the [skip_export](https://www.packer.io/plugins/builders/vmware/iso#skip_export) flag in the build configuration unto which I got an error about using the flag

`
Error: Unsupported argument

  on vsphere_rhel8.pkr.hcl line 84:

  (source code not available)

An argument named "skip_export" is not expected here.
`

With this I am unsure if it is a bug or if it is for the ESX builder only as this setting was underneath the [ISO](https://www.packer.io/plugins/builders/vmware/iso#vmware-builder-from-iso) section of the packer plugins for VMWare.  If this setting is not available for ISO builds is there another setting I am missing or an example config where I can skip saving the ISO at the end

**Comment by tenthirtyam** [comment]
Which release of the `packer-plugin-vsphere` is in use and set in the `required_plugins?`

```hcl
packer {
  required_version = ">= 1.8.3"
  required_plugins {
    vsphere = {
      version = ">= v1.0.8"
      source  = "github.com/hashicorp/vsphere"
    }
  }
}
```

I have no issues with the option in [the project](https://github.com/vmware-samples/packer-examples-for-vsphere) I maintain.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Shocktrooper** [comment]
Apologies but it looks like you are using vsphere instead of the vmware plugin for which this repo is for.  Mind if I ask what is the difference and if I had to migrate what I would have to do?

**Comment by tenthirtyam** [comment]
Ah, my apologies! I totally skipped the mismatch when I reviewed the issue quickly. 

If you want to get started learning the other plugin, which uses the vSphere API and focuses only on vSphere (No Fusion/Workstation), the other project I maintain is a good starting group to help you evaluate the builders and their capabilities.

We (VMware) have some upcoming enhancements that we are make and they will be contributed in the vSphere plugin only.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Shocktrooper** [comment]
Ah perfect thank you!
