### ISSUE TITLE
Avoid forcibly shutting the VM down  when there is no shutdown command

### ISSUE THREAD

**Issue by tiramiseb** [hashicorp/packer-plugin-vmware#97]
#### Description

Ability to disable the feature that forcibly halts the virtual machine.

#### Use Case(s)

I have an automatic installer on an ISO image. I just need Packer to boot the VM, type a command, and then wait for the VM to stop by itself.

While it works perfectly with qemu (no forced shutdown), this plugin forces the shutdown.

A workaround I have found is to define `shutdown_command = "placeholder"` in the source definition (*), but well, it's a bit ugly...

(*): with a fake shutdown command defined but no communicator, it allows [`(*StepShutdown).Run`](https://github.com/hashicorp/packer-plugin-vmware/blob/02e7be06a8d54f855c9c57b675cdd4ea63498c18/builder/vmware/common/step_shutdown.go#L27), to avoid entering in [the `else` block](https://github.com/hashicorp/packer-plugin-vmware/blob/02e7be06a8d54f855c9c57b675cdd4ea63498c18/builder/vmware/common/step_shutdown.go#L73) and not forcibly halt the virtual machine.

**Comment by tenthirtyam** [comment]
I suggest that this is not implemented [based on prior precedent for a similar issue](https://github.com/hashicorp/packer/issues/9362) on `packer-plugin-vsphere`.  This would deviate from the intended use of Packer and this plugin; however, there is an existing workaround.

cc @nywilken for comment.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tiramiseb** [comment]
The issue you are linking here is not similar. That issue is about leaving the VM running forever, and manually stopping it afterwards, which is not what I need.

The `disable_shutdown` option, which is present for `packer-plugin-vsphere`, would be perfectly fine for my need. A 5-minute timeout (configurable with `shutdown_timeout`) is more than enough for my installer.

But that option does not exist on `packer-plugin-vmware`.

**Comment by tenthirtyam** [comment]
In that case such an option may be an option to consider.

**Comment by tenthirtyam** [comment]
Code completed and in local testing prior to pull request.

**Comment by tenthirtyam** [comment]
Closing per https://github.com/hashicorp/packer-plugin-vmware/pull/217#discussion_r1693255029.

**Comment by niall-san** [comment]
I have a build process that ends with a script that sets a static IP and shuts it down afterwards. This is to configure the machine ready to be imported in another location. As the static IP is not valid on my current network, it means Packer is unable to reconnect to run a shutdown command (including a fake one), throwing an error. 

The only option left is to not specify a `shutdown_command` and letting Packer forcefully shutdown the machine, which is not ideal. Is this a valid use case?
